sudo: required
services:
    - docker

before_install:
    - docker build -t danny/react-test -f ./client/Dockerfile.Dev ./client

script:
  - docker run -e CI=true danny/react-test npm test 

after_success:
  - docker build -t krdanny/multi-client ./client
  - docker build -t krdanny/multi-server ./server
  - docker build -t krdanny/multi-worker ./worker
  - docker build -t krdanny/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push krdanny/multi-client
  - docker push krdanny/multi-server
  - docker push krdanny/multi-worker
  - docker push krdanny/multi-nginx